Fix inconsistent behavior for IByteBuffer.Read/WriteBytes(Memory<byte>/Span<byte>)
cuteant/SpanNetty pull request #55
Opened 2021-05-31 04:39 UTC by yyjdelete

2021-05-31 04:46 UTC, yyjdelete commented
@cuteant 
之前测试#51的过程中发现的
WriteBytes写入初始Capacity为0的Buffer会报错,
ReadBytes没有考虑WriterIndex和SlicedByteBuffer的边界
具体的也可以参见我新加的那个测试

但我也不确定现在修改之后的逻辑到底是不是预期的结果

2021-05-31 16:08 UTC, cuteant commented
@yyjdelete 我测试下，这块代码有些绕......

2021-05-31 17:08 UTC, cuteant commented on src/DotNetty.Buffers/AbstractByteBuffer.NetStandard.cs
>              _ = SetBytes(writerIdx, src);
这块保留，EnsureWritable0是不能放在 SetBytes方法中

2021-05-31 17:09 UTC, cuteant commented on src/DotNetty.Buffers/AbstractByteBuffer.NetStandard.cs
>              _ = SetBytes(writerIdx, src);
两个WriteBytes的修改都是正确的

2021-05-31 17:15 UTC, cuteant requested changes

2021-05-31 17:15 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
要增加_GetBytes这种方法，要扩展的类还有好多，不过我建议删除这些修改，只修改两个AbstractByteBuffer.ReadBytes方法，代码如下：
~~~
        public virtual int ReadBytes(Span<byte> destination)
        {
            var readerIndex = _readerIndex;
            var readableBytes = Math.Min(_writerIndex - readerIndex, destination.Length);
            var count = GetBytes(readerIndex, (0u >= (uint)(readableBytes - destination.Length)) ? destination : destination.Slice(0, readableBytes));
            if (count > 0) { _readerIndex += count; }
            return count;
        }
        public virtual int ReadBytes(Memory<byte> destination)
        {
            var readerIndex = _readerIndex;
            var readableBytes = Math.Min(_writerIndex - readerIndex, destination.Length);
            var count = GetBytes(readerIndex, (0u >= (uint)(readableBytes - destination.Length)) ? destination : destination.Slice(0, readableBytes));
            if (count > 0) { _readerIndex += count; }
            return count;
        }
~~~
也就是说，只用修改这 AbstractByteBuffer的ReadBytes、SetBytes、WriteBytes就可以通过你新增的单元测试了

2021-05-31 17:27 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
应该采用 ReadableBytes 属性代替 _writerIndex - readerIndex

2021-06-01 05:56 UTC, yyjdelete commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
我之前想过, 但这样
1. 除非重写所有的SlicedByteBuffer的GetBytes实现, 不然无法保证GetBytes读取的长度会被限制在Slice自身区段内, 而不会泄漏区段外的数据.(好像忘了加测试了)
2. 另外CompositeByteBuffer的GetReadableMemory对于内部有多个buffer的情况不是零拷贝的, 可能还是需要重写方法并使用`GetSequence()`+`System.Buffers.BuffersExtensions.CopyTo<T>(this in ReadOnlySequence<T> source, Span<T> destination)`代替(或者直接基类就用GetSequence

2021-06-01 05:57 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
上面的长度判断有问题，不应该只判断与readablebytes相等的

2021-06-01 06:00 UTC, yyjdelete commented on src/DotNetty.Buffers/AbstractByteBuffer.NetStandard.cs
>              return this;
所有Memory的实现可以考虑直接调用Span的实现来减少重复代码(但因为virtual无法内联, 会存在相应的开销)
public virtual IByteBuffer WriteBytes(in ReadOnlyMemory<byte> src)
    => WriteBytes(src.Span);

2021-06-01 06:05 UTC, yyjdelete commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
`0u >= (uint)xxx` ?
这种好像在其他代码里还有很多

2021-06-01 07:26 UTC, cuteant commented on src/DotNetty.Buffers/AbstractByteBuffer.NetStandard.cs
>              return this;
![image](https://user-images.githubusercontent.com/9393576/120283326-a4a13c80-c2ed-11eb-8c74-25fca3805768.png)

2021-06-01 07:32 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
其他地方应该没啥问题，用到 0U >= (uint)的地方，校验的数值都是要确保值为非负数（>=0）的

2021-06-01 08:00 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
> 我之前想过, 但这样
> 
> 1. 除非重写所有的SlicedByteBuffer的GetBytes实现, 不然无法保证GetBytes读取的长度会被限制在Slice自身区段内, 而不会泄漏区段外的数据.(好像忘了加测试了)
> 2. 另外CompositeByteBuffer的GetReadableMemory对于内部有多个buffer的情况不是零拷贝的, 可能还是需要重写方法并使用`GetSequence()`+`System.Buffers.BuffersExtensions.CopyTo<T>(this in ReadOnlySequence<T> source, Span<T> destination)`代替(或者直接基类就用GetSequence

我之前用手机浏览的，没注意到这条信息，我再想下

2021-06-01 10:19 UTC, yyjdelete commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
>              }
对于`CompositeByteBuffer._GetMemory/_GetSpan`, 如果`ToComponentIndex(index) == ToComponentIndex(index + count - 1)`(即需要获取的内存完整的属于同一区块), 也应该考虑返回数据

2021-06-01 12:06 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
我想了下，当初设计是有些欠妥，之前感觉Span<T>和Memory<T>.Slice用着很方便，
GetBytes(int, Span<byte>),ReadBytes(int, Span<byte>)就放弃显示指定读取长度，而是通过返回值来获取读取长度，所以这几个方法中都放弃使用 CheckReadableBytes 做校验，这样看，逻辑都乱套了，你那样改是对的

2021-06-01 13:26 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
> +        protected internal override void _GetBytes(int index, Span<byte> destination, int length)
> 我之前想过, 但这样
> 
> 1. 除非重写所有的SlicedByteBuffer的GetBytes实现, 不然无法保证GetBytes读取的长度会被限制在Slice自身区段内, 而不会泄漏区段外的数据.(好像忘了加测试了)
> 2. 另外CompositeByteBuffer的GetReadableMemory对于内部有多个buffer的情况不是零拷贝的, 可能还是需要重写方法并使用`GetSequence()`+`System.Buffers.BuffersExtensions.CopyTo<T>(this in ReadOnlySequence<T> source, Span<T> destination)`代替(或者直接基类就用GetSequence

这儿第二点的情况是要在GetSize中使用的时候单独判断 😄

2021-06-01 13:28 UTC, cuteant commented
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/AbstractByteBuffer.NetStandard.cs#L64
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/AbstractByteBuffer.NetStandard.cs#L82
这两个地方也要做 CheckReadableBytes 校验才对

2021-06-01 13:30 UTC, cuteant commented on src/DotNetty.Buffers/CompositeByteBuffer.NetStandard.cs
>              }
对的，当时完全是图省事 👍 😃

2021-06-02 12:56 UTC, cuteant reviewed
后续还会有提交吗？

2021-06-02 14:30 UTC, yyjdelete commented
> 后续还会有提交吗？

在弄了, 之前跑去看tls去了

2021-06-02 15:27 UTC, cuteant commented
这儿修改的ReadBytes/GetBytes要不要也显示指定 readcount，与这儿：
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/AbstractByteBuffer.cs#L451-L455
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/AbstractByteBuffer.cs#L920-L937
逻辑同一起来，然后下面两个方法
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/IByteBuffer.NetStandard.cs#L38
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/IByteBuffer.NetStandard.cs#L42
就可以移除，用扩展方法来实现（调用GetBytes(int index, Span<byte> destSpan, int count)）

2021-06-02 16:03 UTC, cuteant commented
真是搞晕了去，这几个方法
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/IByteBuffer.NetStandard.cs#L34
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/IByteBuffer.NetStandard.cs#L38
不能删除的，可以实现零拷贝嘛  :blush:

2021-06-02 16:23 UTC, yyjdelete commented
1. CompositeByteBuf在可能的情况下尽可能的零拷贝了, 另外补上了之前遗漏的`FixedCompositeByteBuf`, 相应的GetIoBuffer也做了相应调整;
2. Memory的方法暂时没有移到扩展函数里面, 如果移动的话, 源码是兼容的, 但会破坏二进制兼容性, 不过估计使用/重写这个方法的人也不多
3. GetReadableMemory/GetReadableSpan我觉得的确不需要检查CheckReadableBytes啊, 这个风格和其他的GetXxx函数一样, 手动指定了index的都是到Capacity, 而忽略掉WriterIndex的检查; 
而GetReadableSpan和GetSpan的主要区别是, 在CompositeByteBuf中, 不能实现零拷贝时, 前者创建新数组复制后返回(好像可以看做GetIoBuffer的Span版本), 而后者抛出异常

2021-06-02 16:49 UTC, cuteant commented
> 1. CompositeByteBuf在可能的情况下尽可能的零拷贝了, 另外补上了之前遗漏的`FixedCompositeByteBuf`, 相应的GetIoBuffer也做了相应调整;
> 2. Memory的方法暂时没有移到扩展函数里面, 如果移动的话, 源码是兼容的, 但会破坏二进制兼容性, 不过估计使用/重写这个方法的人也不多, 要移的话可以再@我下
> 3. GetReadableMemory/GetReadableSpan我觉得的确不需要检查CheckReadableBytes啊, 这个风格和其他的GetXxx函数一样, 手动指定了index的都是到Capacity, 而忽略掉WriterIndex的检查;
>    而GetReadableSpan和GetSpan的主要区别是, 在CompositeByteBuf中, 不能实现零拷贝时, 前者创建新数组复制后返回(好像可以看做GetIoBuffer的Span版本), 而后者抛出异常
> 4. GetReadableMemory/GetReadableSpan可能可以通过GetSequence来实现?(未测试, 可以参考现在CompositeByteBuffer的逻辑)

前三没问题，第四个我觉得也没必要改了，不同的技术实现，看具体业务具体处理，不是还有 ByteBufferReader 嘛
https://github.com/cuteant/SpanNetty/blob/fdcffd84f68ca4e116fb43ede70b73d1c6d71ce2/src/DotNetty.Buffers/Reader/ByteBufferReader.cs#L37

2021-06-03 00:11 UTC, yyjdelete commented
如果不需要把Get/Read/Write/SetBytes(...Memory)改成扩展函数的话, 那就改完了

2021-06-03 09:23 UTC, cuteant approved these changes
嗯，就这样，先合并

2021-06-03 09:24 UTC, merged